test:
  access_key_id: <%= ENV.fetch('S3_ACCESS_KEY_ID') %>
  secret_access_key: <%= ENV.fetch('S3_SECRET_ACCESS_KEY') %>
development:
  access_key_id: <%= ENV.fetch('S3_ACCESS_KEY_ID') %>
  secret_access_key: <%= ENV.fetch('S3_SECRET_ACCESS_KEY') %>
production:
  access_key_id: <%= ENV.fetch('S3_ACCESS_KEY_ID') %>
  secret_access_key: <%= ENV.fetch('S3_SECRET_ACCESS_KEY') %>
